### ISSUE TITLE
execute issue

### ISSUE THREAD

**Issue by Eric-Hsia** [3D-Printing-for-Microfluidics/OpenGL-STL-slicer#1]
你好，我用你的C++版本编译后执行程序有下面问题，请问是啥原因呢？谢谢

![issue](https://user-images.githubusercontent.com/20067709/38240428-2762156a-3762-11e8-8e9e-8a1304233a38.jpg)

**Comment by GNHua** [comment]
我用英文回复你，这样别人看到说不定能帮到你。
I just complied it on my Mac. It works fine. C++ version is an exercise for me to learn OpenGL, so I have only tested it on Mac. But I have tested the Python version on Mac, Windows 7, and Linux/Ubuntu.

**Comment by Eric-Hsia** [comment]
Thanks
